import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const base=process.env.EXPLOREOS_TEST_URL;
const browser=await chromium.launch({headless:true,channel:'msedge'});
try{
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  const page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('dialog',dialog=>dialog.accept());
  const action=name=>page.locator(`[data-action="${name}"]`).first();
  const navigate=view=>page.locator(`[data-view="${view}"]:visible`).first().click();
  const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('exploreos.v1')));
  const save=async()=>{await page.getByRole('button',{name:'保存',exact:true}).click();await page.locator('#dialog').waitFor({state:'hidden'});};
  const synced=()=>page.waitForFunction(()=>document.querySelector('.local-dot').textContent.startsWith('本机已保存'));
  await page.goto(base);
  await action('note').click();
  await page.locator('#f-text').fill('看了一段访谈，我对普通工作日的样子好奇。');
  await save();await synced();
  assert.equal((await state()).experiments.length,0);
  assert.equal((await state()).notes.length,1);
  await page.reload();
  await navigate('journal');
  assert.equal(await page.locator('[data-note]').count(),1);
  await page.screenshot({path:'tests/v04-journal.png',fullPage:true});
  await action('edit-note').click();
  await page.locator('#f-text').fill('未完成的随手记草稿');
  await page.locator('#close-dialog').click();
  await page.reload();await navigate('journal');await action('edit-note').click();
  assert.equal(await page.locator('#f-text').inputValue(),'未完成的随手记草稿');
  await page.locator('#discard-draft').click();
  await navigate('guide');
  const initial=await state();
  await page.locator('[data-guide-pref="directionId"]').selectOption('sample:艺术与摄影');
  await page.locator('[data-guide-pref="mode"]').selectOption('make');
  assert.match(await page.locator('.guide-steps').innerText(),/照片/);
  await page.screenshot({path:'tests/v04-guide.png',fullPage:true});
  await page.locator('[data-guide-pref="directionId"]').selectOption('sample:运动体验');
  assert.match(await page.locator('.guide-steps').innerText(),/轻松走/);
  assert.deepEqual(await state(),initial,'Browsing samples must not create directions.');
  const rejectedTitle=await page.locator('.guide-card h2').innerText();
  await action('guide-later').click();
  assert.notEqual(await page.locator('.guide-card h2').innerText(),rejectedTitle);
  await action('guide-tried').click();
  assert.match(await page.locator('#content').innerText(),/这一组建议已经看过/);
  await page.reload();await navigate('guide');
  await page.locator('[data-guide-pref="directionId"]').selectOption('sample:运动体验');
  await page.locator('[data-guide-pref="mode"]').selectOption('make');
  assert.match(await page.locator('#content').innerText(),/这一组建议已经看过/);
  await action('guide-reset').click();
  await action('guide-experiment').click();
  assert.equal(await page.locator('#f-directionId').inputValue(),'');
  await save();await synced();
  assert.ok((await state()).directions.some(d=>d.name==='运动体验'));
  await navigate('journal');await action('attach-note').click();await save();await synced();
  assert.equal((await state()).notes[0].text,initial.notes[0].text);
  assert.equal((await state()).sessions.length,1);
  assert.equal(await page.locator('[data-action="attach-note"]').count(),0);
  await page.reload();await synced();

  // A second browser has an independent old copy, even after a reload.
  const other=await browser.newContext(),second=await other.newPage();
  await second.goto(base);
  await second.evaluate(raw=>localStorage.setItem('exploreos.v1',raw),JSON.stringify(await state()));
  await second.reload();
  await second.waitForFunction(()=>document.querySelector('.local-dot').textContent.startsWith('本机已保存'));
  await action('note').click();await page.locator('#f-text').fill('新浏览器里的新经历');await save();await synced();
  const newest=await (await page.request.get(base+'/api/state')).json();
  await second.reload();
  await second.locator('[data-action="note"]').first().click();
  await second.locator('#f-text').fill('旧浏览器里仍想保留的想法');
  await second.getByRole('button',{name:'保存',exact:true}).click();
  await second.locator('#dialog').waitFor({state:'hidden'});
  await second.waitForFunction(()=>document.querySelector('.local-dot').textContent.includes('版本冲突'));
  assert.equal((await (await page.request.get(base+'/api/state')).json()).latest.revision,newest.latest.revision);
  assert.ok(await second.evaluate(()=>JSON.parse(localStorage.getItem('exploreos.v1')).notes.some(n=>n.text==='旧浏览器里仍想保留的想法')));
  await second.locator('[data-view="backup"]:visible').first().click();
  assert.match(await second.locator('.backup-error').innerText(),/已阻止覆盖/);
  let acceptOverwrite=false;
  second.on('dialog',dialog=>acceptOverwrite?dialog.accept():dialog.dismiss());
  await second.locator('[data-action="sync-disk"]').click();
  await second.waitForFunction(()=>document.querySelector('.local-dot').textContent.includes('副本不同'));
  assert.equal((await (await page.request.get(base+'/api/state')).json()).latest.revision,newest.latest.revision,'Cancel must preserve the disk version.');
  acceptOverwrite=true;
  const diskSafetyCopy=second.waitForEvent('download');
  await second.locator('[data-action="sync-disk"]').click();
  assert.match((await diskSafetyCopy).suggestedFilename(),/disk-before-update/);
  await second.waitForFunction(()=>document.querySelector('.local-dot').textContent.startsWith('本机已保存'));
  const resolved=await (await page.request.get(base+'/api/state')).json();
  assert.ok(resolved.latest.state.notes.some(n=>n.text==='旧浏览器里仍想保留的想法'));
  assert.ok(resolved.previous.state.notes.some(n=>n.text==='新浏览器里的新经历'));
  await other.close();

  await page.reload();
  await page.waitForFunction(()=>document.querySelector('.local-dot').textContent.includes('副本不同'));
  await navigate('backup');
  const disk=await (await page.request.get(base+'/api/state')).json();
  assert.ok(disk.history.length>=3);
  await page.locator('.history-list summary').click();
  const oldHistory=disk.history.at(-1);
  const safeDownload=page.waitForEvent('download');
  await page.locator(`[data-action="restore-history"][data-id="${oldHistory.name}"]`).click();
  assert.match((await safeDownload).suggestedFilename(),/before-disk-restore/);
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('exploreos.v1')).notes.length===1);
  await synced();
  assert.equal((await state()).experiments.length,0);
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await navigate('guide');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await navigate('journal');await action('note').click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#close-dialog').click();
  assert.deepEqual(errors,[]);
  await context.close();
  console.log('v0.4 browser checks passed: independent notes, drafts, direction-specific suggestions, persistent feedback, sample creation, note conversion, stale-browser protection, history recovery and mobile layout.');
}finally{await browser.close();}
