import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const base=process.env.EXPLOREOS_TEST_URL||'http://localhost:4173';
const browser=await chromium.launch({headless:true,channel:'msedge'});
try{
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('dialog',dialog=>dialog.accept());
  const action=(name,id)=>page.locator(`[data-action="${name}"]${id?`[data-id="${id}"]`:''}`).first();
  const navigate=view=>page.locator(`[data-view="${view}"]:visible`).first().click();
  const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('exploreos.v1')));
  const synced=()=>page.waitForFunction(()=>document.querySelector('.local-dot').textContent.startsWith('本机已保存'));
  const save=async()=>{await page.getByRole('button',{name:'保存',exact:true}).click();await page.locator('#dialog').waitFor({state:'hidden'});await synced();};
  await page.goto(base);
  await action('note').click();await page.locator('#f-text').fill('听了访谈 <script>仅作为文字</script>');await save();
  const note=(await state()).notes[0],before=await state();
  await navigate('journal');await action('note-experiment',note.id).click();
  assert.match(await page.locator('#fields').innerText(),/同时建立实验/);
  await page.locator('#f-title').fill('了解一个普通工作日');
  await page.locator('details.optional-fields summary').click();
  await page.locator('#f-nextAction').fill('聊一聊最有意思的环节');
  await page.locator('#f-completion').fill('记下一件想亲手尝试的事');
  await page.locator('#close-dialog').click();
  assert.deepEqual(await state(),before,'Closing a conversion draft must not create an experiment or a record.');
  await page.reload();await synced();await navigate('journal');await action('note-experiment',note.id).click();
  assert.equal(await page.locator('#f-nextAction').inputValue(),'聊一聊最有意思的环节');
  await page.evaluate(()=>{
    window.coreOriginalSetItem=Storage.prototype.setItem;
    Storage.prototype.setItem=function(key,value){if(key==='exploreos.v1')throw new DOMException('Quota exceeded','QuotaExceededError');return window.coreOriginalSetItem.call(this,key,value);};
  });
  await page.getByRole('button',{name:'保存',exact:true}).click();
  assert.match(await page.locator('#form-error').innerText(),/本次没有保存/);
  assert.deepEqual(await state(),before,'A failed save must not leave a partial conversion.');
  await page.evaluate(()=>{Storage.prototype.setItem=window.coreOriginalSetItem;delete window.coreOriginalSetItem;});
  await save();
  let current=await state();const experimentId=current.experiments[0].id;
  assert.equal(current.experiments.length,1);assert.equal(current.sessions.length,1);
  assert.equal(current.notes[0].sessionId,current.sessions[0].id);
  assert.equal(current.sessions[0].action,note.text);assert.equal(current.sessions[0].minutes,null);
  assert.equal(current.experiments[0].completion,'记下一件想亲手尝试的事');
  assert.match(await page.locator('.experiment-plan').innerText(),/聊一聊最有意思的环节/);
  await navigate('journal');assert.equal(await page.locator('[data-action="note-experiment"]').count(),0);
  await navigate('experiments');await action('review',experimentId).click();
  assert.match(await page.locator('#fields').innerText(),/记下一件想亲手尝试的事/);
  await page.locator('#f-reflection').fill('我更想体验真实工作中的一个任务');
  await page.locator('#f-nextAction').fill('试着完成一个小任务 <img src=x onerror=alert(1)>');
  await save();
  const memory=structuredClone((await state()).memories[0]);
  assert.equal(memory.nextAction,(await state()).experiments[0].nextAction);
  await navigate('map');assert.match(await page.locator('.next-action').innerText(),/试着完成一个小任务/);
  await navigate('experiments');await action('edit-experiment',experimentId).click();
  await page.locator('#f-hypothesis').fill('修改后的新问题');
  await page.locator('#f-completion').fill('修改后的新标准');
  await save();
  assert.deepEqual((await state()).memories[0],memory);
  await navigate('memories');
  assert.match(await page.locator('.memory').innerText(),/记下一件想亲手尝试的事/);
  assert.equal(await page.locator('#content img,#content script').count(),0);
  const exported=page.waitForEvent('download');await action('export-memory').click();
  const text=await readFile(await (await exported).path(),'utf8');
  assert.match(text,/留给下次的小行动/);assert.match(text,/记下一件想亲手尝试的事/);
  await navigate('experiments');await action('review',experimentId).click();
  await page.locator('#f-reflection').fill('现在先放一放');await page.locator('#f-decision').selectOption('hold');
  await page.locator('#f-nextAction').fill('');await save();
  assert.equal((await state()).experiments[0].nextAction,'');assert.equal((await state()).experiments[0].status,'hold');
  assert.deepEqual((await state()).memories[0],memory);
  await navigate('problems');await action('problem').click();
  await page.locator('#f-text').fill('想知道这项工作的日常');await save();
  const problemId=(await state()).problems[0].id;
  await action('problem-experiment',problemId).click();await save();
  current=await state();const linked=current.experiments.find(e=>e.sourceProblemId===problemId);
  assert.ok(linked);assert.equal(current.problems.length,1);
  await action('open-problem',problemId).click();
  assert.equal(await page.locator(':focus').getAttribute('data-problem'),problemId);
  assert.match(await page.locator(`[data-problem="${problemId}"]`).innerText(),/已经开始 1 个相关实验/);
  await action('open-experiment',linked.id).click();
  assert.equal(await page.locator('[data-experiment]').count(),1);
  await action('open-problem',problemId).click();await action('trash-problems',problemId).click();await synced();
  await navigate('experiments');assert.match(await page.locator(`[data-experiment="${linked.id}"]`).innerText(),/来源问题在回收站中/);
  await navigate('backup');await action('restore-problems',problemId).click();await synced();
  await navigate('experiments');await action('trash-experiments',linked.id).click();await synced();
  await navigate('problems');assert.match(await page.locator(`[data-problem="${problemId}"]`).innerText(),/1 个相关实验在回收站中/);
  await navigate('backup');await action('restore-experiments',linked.id).click();await synced();
  await navigate('guide');
  const steps=await page.locator('.guide-steps li').allTextContents();
  await action('guide-experiment').click();
  assert.equal(await page.locator('#f-nextAction').inputValue(),steps.map((step,i)=>`${i+1}. ${step}`).join('\n'));
  assert.ok(await page.locator('#f-completion').inputValue());await save();
  const backup=(await (await page.request.get(base+'/api/state')).json()).latest.state;
  assert.deepEqual(backup,await state(),'New plan fields, source links and review snapshots must persist to disk.');
  await navigate('memories');await action('open-experiment',experimentId).click();
  await page.screenshot({path:'tests/core-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'tests/core-mobile.png',fullPage:true});
  await action('review',experimentId).click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#close-dialog').click();
  assert.deepEqual(errors,[]);
  await context.close();
  console.log('Core browser checks passed: note-to-experiment draft and atomic save, plans, next-action review, immutable snapshots, Markdown, problem links and trash recovery, guide plan persistence, disk backup and mobile layout.');
}finally{await browser.close();}
