import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {initialState,attachNote,makeMemory} from '../model.js';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const browser=await chromium.launch({headless:true,channel:'msedge'});
try{
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  const page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  const seed=initialState(),directionId=seed.directions[0].id;
  seed.experiments=['e1','e2'].map(id=>({id,directionId,title:'同名实验 <script>不会执行</script>',hypothesis:'',status:'active',budget:null,createdAt:'2026-10-01'}));
  seed.notes=[{id:'n',text:'原随手记 <img src=x onerror=alert(1)>',date:'2026-10-06',directionId:null,sessionId:null,createdAt:'2026-10-06T08:00:00Z',updatedAt:'2026-10-06T08:00:00Z'},
    {id:'free',text:'暂未整理的想法',date:'2026-10-07',directionId:null,sessionId:null,createdAt:'2026-10-07T08:00:00Z',updatedAt:'2026-10-07T08:00:00Z'}];
  const data=attachNote(seed,'n','e2');
  data.sessions[0].skills=['观察'];
  data.memories=[makeMemory(data,'e2','hold','保留这一段经历')];
  const recordId=data.sessions[0].id;
  await page.addInitScript(data=>localStorage.setItem('exploreos.v1',JSON.stringify(data)),data);
  await page.goto(process.env.EXPLOREOS_TEST_URL||'http://localhost:4173');
  await page.waitForFunction(()=>document.querySelector('.local-dot').textContent.startsWith('本机已保存'));
  const navigate=view=>page.locator(`[data-view="${view}"]:visible`).first().click();
  const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('exploreos.v1')));
  await navigate('journal');
  await page.locator('#journal-kind').selectOption('unfiled');
  assert.equal(await page.locator('[data-note]').count(),1);
  assert.equal(await page.locator('[data-note]').getAttribute('data-note'),'free');
  assert.equal(await page.locator('[data-record]').count(),0);
  await page.locator('#journal-kind').selectOption('session');
  await page.locator('#journal-from').fill('2026-10-06');
  await page.locator('#journal-to').fill('2026-10-06');
  await page.locator('#search').fill('观察');
  await page.locator('#direction-filter').selectOption(directionId);
  assert.equal(await page.locator('[data-record]').count(),1);
  await page.locator('#journal-from').fill('2026-10-07');
  assert.match(await page.locator('#content [role="alert"]').innerText(),/开始日期不能晚于结束日期/);
  assert.equal(await page.locator('[data-record]').count(),0);
  await page.locator('[data-action="clear-journal-filters"]').first().click();
  assert.equal(await page.locator('#search').inputValue(),'');
  assert.equal(await page.locator('#direction-filter').inputValue(),'');
  assert.equal(await page.locator('#journal-from').inputValue(),'');
  assert.equal(await page.locator('[data-note]').count(),2);
  await page.locator('[data-note="n"] [data-action="open-session"]').click();
  assert.equal(await page.locator(':focus').getAttribute('data-record'),recordId);
  await page.locator(`[data-record="${recordId}"] [data-action="open-note"]`).click();
  assert.equal(await page.locator(':focus').getAttribute('data-note'),'n');
  await page.locator(`[data-record="${recordId}"] [data-action="open-experiment"]`).click();
  assert.equal(await page.locator('[data-experiment]').count(),1);
  assert.equal(await page.locator('[data-experiment]').getAttribute('data-experiment'),'e2');
  await page.locator('[data-action="go-experiments"]').click();
  assert.equal(await page.locator('[data-experiment]').count(),2);
  await navigate('skills');
  await page.locator('summary').click();
  await page.locator('[data-action="open-experiment"]').click();
  assert.equal(await page.locator('[data-experiment]').getAttribute('data-experiment'),'e2');
  assert.deepEqual(await state(),data,'Filtering and navigating must not write personal data.');
  await navigate('journal');
  await page.locator(`[data-record="${recordId}"] [data-action="trash-sessions"]`).click();
  assert.match(await page.locator('[data-note="n"]').innerText(),/在回收站中/);
  assert.equal(await page.locator('[data-action="attach-note"][data-id="n"]').count(),0);
  await page.locator('[data-note="n"] [data-action="go-backup"]').click();
  await page.locator(`[data-action="restore-sessions"][data-id="${recordId}"]`).click();
  await navigate('journal');
  assert.equal(await page.locator('[data-note="n"] [data-action="open-session"]').count(),1);
  assert.deepEqual((await state()).memories,data.memories);
  assert.equal(await page.locator('#content script,#content img').count(),0);
  await page.setViewportSize({width:390,height:844});
  await page.locator('#journal-kind').selectOption('note');
  await page.locator('#journal-from').fill('2026-10-06');
  await page.locator('#journal-to').fill('2026-10-07');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'tests/review-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'tests/review-desktop.png',fullPage:true});
  assert.deepEqual(errors,[]);
  await context.close();
  console.log('Review browser checks passed: combined filters, date errors, clear filters, exact links, trash recovery, immutable snapshots, safe text and mobile layout.');
}finally{await browser.close();}
